#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), "../boot"))

require 'spork/runner'
require 'spork/test_framework/minitest'

begin
  success = Spork::Runner.run(ARGV, STDOUT, STDERR)
  Kernel.exit(success ? 0 : 1)
rescue SystemExit => e
  Kernel.exit(e.status)
rescue Exception => e
  STDERR.puts("#{e.message} (#{e.class})")
  STDERR.puts(e.backtrace.join("\n"))
  Kernel.exit 1
end

