#!/usr/bin/env ruby

# Spork looks at the gems installed either using bundler or Gem for files in
# space of "spork/test_framework/*"
require 'spork'

begin
  success = Spork::Runner.run(ARGV, STDOUT, STDERR)
  Kernel.exit(success ? 0 : 1)
rescue SystemExit => e
  Kernel.exit(e.status)
rescue Exception => e
  STDERR.puts("#{e.message} (#{e.class})")
  STDERR.puts(e.backtrace.join("\n"))
  Kernel.exit 1
end

